# Generated by Django 3.0.6 on 2021-05-02 18:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_saleorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Car'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Showroom'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Mini', 'Savings with Mini Car'), ('Go', 'AC Car'), ('Go Plus', 'Luxurous Car')], max_length=100),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='Order_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
