# Generated by Django 3.0.6 on 2021-05-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_car_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
