# Generated by Django 3.0.6 on 2021-05-04 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cost_par_day',
            field=models.IntegerField(),
        ),
    ]
