# Generated by Django 3.0.6 on 2021-05-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20210504_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
