# Generated by Django 3.0.6 on 2021-05-04 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20210504_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='showroom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Showroom'),
        ),
    ]
