# Generated by Django 3.0.6 on 2021-05-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_car_showroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='available',
            field=models.CharField(default='Available', max_length=50),
        ),
    ]
