# Generated by Django 3.0.6 on 2021-05-04 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_car_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='salesman',
        ),
    ]
