# Generated by Django 3.0.6 on 2021-05-05 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_saleorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='system.Showroom'),
        ),
    ]
