# Generated by Django 3.0.6 on 2021-05-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_auto_20210506_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='Deliver_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='Order_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
