# Generated by Django 3.0.6 on 2021-05-11 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_auto_20210506_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)]),
        ),
    ]
