# Generated by Django 3.0.6 on 2021-05-02 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('Accounts', '0003_auto_20210502_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='works_at_showroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works_at', to='system.Showroom'),
        ),
    ]
