# Generated by Django 3.0.6 on 2021-05-04 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20210504_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='password',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
