# Generated by Django 3.0.6 on 2021-05-04 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_auto_20210504_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(15)]),
        ),
    ]
